sudo: required
services:
  - docker

before_install:
  - docker build -t nafzaltx/docker-react-july2019 -f Dockerfile.dev .

script:
  - docker run nafzaltx/docker-react-july2019 npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "dockerReactJuly2019"
  env: "Dockerreactjuly2019-env"
  bucket_name: "elasticbeanstalk-us-east-2-150460661407"
  bucket_path: "dockerReactJuly2019"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
